---
- name: User setup
  hosts: localhost
  become: true
  tasks:
      - name: Add developers to production box
        user:
          name: "{{ item }}"
          state: present
          groups: "admin"
        loop:
          - dev1
          - dev2
          - dev3
          - dev4
        tags: add-users