---
- name: User setup
  become_method: sudo
  hosts: nginx-one-host
  vars_files:
    - vars/users.yml
  tasks:

    - name: Add group "admin"
      group:
        name: admin
        state: present
      tags: add-group

    - name: Add developers to production box
      user:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        groups: "{{ item.group }}"
      with_items: "{{ users }}"
      tags: add-users

    - name: Add developer keys to production box
      authorized_key:
        key: "{{ lookup('file', 'public_keys/' + item.name + '.pub') }}"
        user: "{{ item.name }}"
        comment: "{{ item.name }}"
        manage_dir: yes
        state: "{{ item.state }}"
      with_items: "{{ users }}"
      tags: add-keys

    - name: Revoke developer keys from production box
      authorized_key:
        key: "{{ lookup('file', 'public_keys/' + item.name + '.pub') }}"
        user: "{{ item.name }}"
        comment: "{{ item.name }}"
        manage_dir: yes
        state: "{{ item.state }}"
      with_items: "{{ remove_users }}"
      tags: revoke-keys