---
- name: User setup
  hosts: localhost
  become: yes
  become_user: root
  vars_files:
    - vars/users.yml
  tasks:
    - name: Add developers to production box
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      with_items: "{{ users }}"
      tags: add-users